
def additoin(x, y):
    x = 10
    y = 20
    print("Addition:", x + b)

try :
    additoin(10, 20)

except NameError :
    print(NameError)

except Exception as e : 
    print("something went wrong ,",e)

else : 
    print ('the operation is successful')



